services:
  - type: web
    name: blitz-playground
    env: node
    plan: starter
    buildCommand: yarn; blitz db migrate; blitz build
    startCommand: blitz start --production -H 0.0.0.0
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blitz-playground-db
          property: connectionString
databases:
  - name: blitz-playground-db
    plan: starter
